select s.STUDENTNAME as StudentName, max(MAX_GRADE) as Grade, c.COURSETITLE as CourseTitle  from (select STUDENTID, max(GRADEASPERCENTAGE) as MAX_GRADE
from REGISTRATION r group by STUDENTID ) a1, REGISTRATION r, STUDENT s, COURSE c, OFFERING o
where a1.MAX_GRADE = r.GRADEASPERCENTAGE
and r.OFFERINGID = o.OFFERINGID
and a1.STUDENTID = s.STUDENTID
and c.COURSEID = o.COURSEID
group by s.STUDENTNAME, c.COURSETITLE
order by s.STUDENTNAME;